# Site settings
name: Pronoy Chaudhuri
title: Pronoy | Product Manager
description: Product manager adamant on creating amazing products
url: https://www.pronoy.ca/
baseurl: ""
email: pronoy.chaudhuri@uwaterloo.ca
cover: https://www.pronoy.ca/img/og.png
logo: https://www.pronoy.ca/img/emojis/technologist.png
resume: https://www.pronoy.ca/resume.pdf
social:
  - title: email
    url: mailto:pronoy.chaudhuri@uwaterloo.ca
  - title: github
    url: https://github.com/PronoyC
  - title: medium
    url: https://medium.com/@pronoyc
  - title: linkedin
    url: https://www.linkedin.com/in/pronoyc/

# Build settings
markdown: kramdown

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gemspec"
  - "README.md"
  - "node_modules"
  - "build"
  - "gulpfile.js"
  - "package.json"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
