# Site settings
name: Pronoy Chaudhuri
title: Pronoy Chaudhuri | Full-Stack Developer
description: Blockchain-focused full-stack developer adamant on creating meaningful code
url: https://www.pronoy.me/
baseurl: ""
email: pronoy.chaudhuri@uwaterloo.ca
cover: https://www.pronoy.me/img/og.png
logo: https://www.pronoy.me/img/emojis/technologist.png
resume: https://www.pronoy.me/resume.pdf
social:
  - title: email
    url: mailto:pronoy.chaudhuri@uwaterloo.ca
  - title: twitter
    url: https://twitter.com/Pronoy_C
  - title: instagram
    url: https://www.instagram.com/pronoy_c/
  - title: github
    url: https://github.com/PronoyC
  - title: linkedin
    url: https://www.linkedin.com/in/pronoyc/

# Build settings
markdown: kramdown

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gemspec"
  - "README.md"
  - "node_modules"
  - "build"
  - "gulpfile.js"
  - "package.json"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
